// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mock is a generated GoMock package.
package mock

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockGRPCServer is a mock of GRPCServer interface.
type MockGRPCServer struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCServerMockRecorder
}

// MockGRPCServerMockRecorder is the mock recorder for MockGRPCServer.
type MockGRPCServerMockRecorder struct {
	mock *MockGRPCServer
}

// NewMockGRPCServer creates a new mock instance.
func NewMockGRPCServer(ctrl *gomock.Controller) *MockGRPCServer {
	mock := &MockGRPCServer{ctrl: ctrl}
	mock.recorder = &MockGRPCServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCServer) EXPECT() *MockGRPCServerMockRecorder {
	return m.recorder
}

// GetListener mocks base method.
func (m *MockGRPCServer) GetListener() net.Listener {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListener")
	ret0, _ := ret[0].(net.Listener)
	return ret0
}

// GetListener indicates an expected call of GetListener.
func (mr *MockGRPCServerMockRecorder) GetListener() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListener", reflect.TypeOf((*MockGRPCServer)(nil).GetListener))
}

// GetServer mocks base method.
func (m *MockGRPCServer) GetServer() *grpc.Server {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServer")
	ret0, _ := ret[0].(*grpc.Server)
	return ret0
}

// GetServer indicates an expected call of GetServer.
func (mr *MockGRPCServerMockRecorder) GetServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockGRPCServer)(nil).GetServer))
}

// SERVE mocks base method.
func (m *MockGRPCServer) SERVE() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SERVE")
}

// SERVE indicates an expected call of SERVE.
func (mr *MockGRPCServerMockRecorder) SERVE() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SERVE", reflect.TypeOf((*MockGRPCServer)(nil).SERVE))
}
